### ISSUE TITLE
Install bug

### ISSUE THREAD

**Issue by airqui** [DQM4HEP/DQM4HEP#3]
Dear all,
This morning, I tried to install it, unsuccesfully, in my office PC (Ubuntu 14). The error appears when compiling the dim libraries and/or the LCIO documentation.  

I use 
ROOT 5.34/30
cmake version 2.8.12.2

Please find enclosed the cmake and make outputs for three cases. I have also tried to compile it not standalone but with the ilcsoft libraries, with similar results.

The cases are:

1)ERRORS compiling DIM
cmake -DDQM4HEP_LCIO=OFF -DDQM4HEP_EXAMPLES=ON -DINSTALL_DOC=ON -DDQM4HEP_VIZ=ON ..

2) ERROR in the LCIO documentation
cmake -DDQM4HEP_LCIO=ON -DDQM4HEP_EXAMPLES=ON -DINSTALL_DOC=ON -DDQM4HEP_VIZ=ON ..

3) ERRORS in the JSON related libraries (no doc or LCIO installation) 
cmake -DDQM4HEP_LCIO=OFF -DDQM4HEP_EXAMPLES=ON -DINSTALL_DOC=OFF -DDQM4HEP_VIZ=ON ..

########################################################
ERRORS compiling DIM

airqui@flc58:/space/airqui/Programs/DQM4HEP/build$ cmake -DDQM4HEP_LCIO=OFF -DDQM4HEP_EXAMPLES=ON -DINSTALL_DOC=ON -DDQM4HEP_VIZ=ON ..
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- DQM4HEP_VIZ: ON
-- DQM4HEP_LCIO: OFF
-- DQM4HEP_ELOG: OFF
-- DQM4HEP_EXAMPLES: ON
-- ILCSOFT not found
-- Found Git: /usr/bin/git (found version "1.9.1") 
-- Could NOT find DIM_SHARED (missing:  DIM_SHARED_LIBRARY DIM_INCLUDE_DIR) 
-- Could NOT find DIM (missing:  DIM_LIBRARIES DIM_INCLUDE_DIR) 
-- Could NOT find DIMJC (missing:  DIMJC_LIBRARIES DIMJC_INCLUDE_DIRS) 
-- Check for DIMJC_INCLUDE_DIRS: DIMJC_INCLUDE_DIRS-NOTFOUND
-- Check for DIMJC_LIBRARIES: DIMJC_LIBRARY-NOTFOUND
-- 
-- -------------------------------------------------------------------------------
-- Change values with: cmake -D<Variable>=<Value>
-- CMAKE_INSTALL_PREFIX = /space/airqui/Programs/DQM4HEP
-- CMAKE_BUILD_TYPE = RelWithDebInfo
-- BUILD_TESTING = ON
-- INSTALL_DOC = ON
-- CMAKE_MODULE_PATH =
--    /space/airqui/Programs/DQM4HEP/cmake;
-- -------------------------------------------------------------------------------
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /space/airqui/Programs/DQM4HEP/build

-----> ERRORS during make:

-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found DIM_SHARED: /space/airqui/Programs/DQM4HEP/dim/linux/libdim.so  
-- Found DIM: /space/airqui/Programs/DQM4HEP/dim/linux/libdim.so  
-- Found JSONCpp: /space/airqui/Programs/DQM4HEP/lib/libjsoncpp.so
-- 
-- -------------------------------------------------------------------------------
-- Change values with: cmake -D<Variable>=<Value>
-- CMAKE_INSTALL_PREFIX = /space/airqui/Programs/DQM4HEP
-- CMAKE_BUILD_TYPE = RelWithDebInfo
-- BUILD_TESTING = ON
-- INSTALL_DOC = ON
-- CMAKE_PREFIX_PATH =
-- CMAKE_MODULE_PATH =
--    /space/airqui/Programs/DQM4HEP/cmake;
--    /space/airqui/Programs/DQM4HEP/dimjc/cmake;
-- -------------------------------------------------------------------------------

[ 79%] Performing build step for 'dimjc'
Scanning dependencies of target dimjc
[ 33%] Building CXX object CMakeFiles/dimjc.dir/src/DimJobControl.cc.o
/space/airqui/Programs/DQM4HEP/dimjc/src/DimJobControl.cc:34:33: warning: ISO C does not permit named variadic macros [-Wvariadic-macros]
 #define DEBUG_PRINT(format, args...) ((void)0)
                                 ^
/space/airqui/Programs/DQM4HEP/dimjc/src/DimJobControl.cc: In member function ‘void DimJobControl::startProcess(DimProcessData*)’:
/space/airqui/Programs/DQM4HEP/dimjc/src/DimJobControl.cc:297:44: warning: format not a string literal and no format arguments [-Wformat-security]
  sprintf(executivePath, programName.c_str());
                                            ^
[ 66%] Building CXX object CMakeFiles/dimjc.dir/src/DimJobInterface.cc.o
/space/airqui/Programs/DQM4HEP/dimjc/src/DimJobInterface.cc: In member function ‘void DimJobInterface::loadJSON(const string&)’:
/space/airqui/Programs/DQM4HEP/dimjc/src/DimJobInterface.cc:54:42: warning: ‘std::string Json::Reader::getFormatedErrorMessages() const’ is deprecated (declared at /space/airqui/Programs/DQM4HEP/include/json/reader.h:102): Use getFormattedErrorMessages() instead. [-Wdeprecated-declarations]
       << reader.getFormatedErrorMessages()
                                          ^
Linking CXX shared library lib/libdimjc.so
[ 66%] Built target dimjc
Scanning dependencies of target dimjc_daemon
[100%] Building CXX object CMakeFiles/dimjc_daemon.dir/src/djc.cxx.o
Linking CXX executable bin/dimjc_daemon
/space/airqui/Programs/DQM4HEP/dim/linux/libdim.so: undefined reference to `sem_init'
/space/airqui/Programs/DQM4HEP/dim/linux/libdim.so: undefined reference to `sem_destroy'
/space/airqui/Programs/DQM4HEP/dim/linux/libdim.so: undefined reference to `pthread_create'
/space/airqui/Programs/DQM4HEP/dim/linux/libdim.so: undefined reference to `pthread_cancel'
/space/airqui/Programs/DQM4HEP/dim/linux/libdim.so: undefined reference to `sem_post'
/space/airqui/Programs/DQM4HEP/dim/linux/libdim.so: undefined reference to `sem_wait'
/space/airqui/Programs/DQM4HEP/dim/linux/libdim.so: undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[5]: *** [bin/dimjc_daemon] Error 1
make[4]: *** [CMakeFiles/dimjc_daemon.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [dimjc/src/dimjc-stamp/dimjc-build] Error 2
make[1]: *** [CMakeFiles/dimjc.dir/all] Error 2
make: *** [all] Error 2

########################################################
ERROR in the LCIO documentation

airqui@flc58:/space/airqui/Programs/DQM4HEP/build$ cmake -DDQM4HEP_LCIO=ON -DDQM4HEP_EXAMPLES=ON -DINSTALL_DOC=ON -DDQM4HEP_VIZ=ON ..
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- DQM4HEP_VIZ: ON
-- DQM4HEP_LCIO: ON
-- DQM4HEP_ELOG: OFF
-- DQM4HEP_EXAMPLES: ON
-- ILCSOFT not found
-- Found Subversion: /usr/bin/svn (found version "1.8.8") 
-- Found Git: /usr/bin/git (found version "1.9.1") 
-- Could NOT find DIM_SHARED (missing:  DIM_SHARED_LIBRARY DIM_INCLUDE_DIR) 
-- Could NOT find DIM (missing:  DIM_LIBRARIES DIM_INCLUDE_DIR) 
-- Could NOT find DIMJC (missing:  DIMJC_LIBRARIES DIMJC_INCLUDE_DIRS) 
-- Check for DIMJC_INCLUDE_DIRS: DIMJC_INCLUDE_DIRS-NOTFOUND
-- Check for DIMJC_LIBRARIES: DIMJC_LIBRARY-NOTFOUND
-- 
-- -------------------------------------------------------------------------------
-- Change values with: cmake -D<Variable>=<Value>
-- CMAKE_INSTALL_PREFIX = /space/airqui/Programs/DQM4HEP
-- CMAKE_BUILD_TYPE = RelWithDebInfo
-- BUILD_TESTING = ON
-- INSTALL_DOC = ON
-- CMAKE_MODULE_PATH =
--    /space/airqui/Programs/DQM4HEP/cmake;
-- -------------------------------------------------------------------------------
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /space/airqui/Programs/DQM4HEP/build

...

-- Set runtime path of "/space/airqui/Programs/DQM4HEP/bin/readcalibration" to "/space/airqui/Programs/DQM4HEP/lib"
CMake Error at doc/cmake_install.cmake:36 (FILE):
  file INSTALL cannot find
  "/space/airqui/Programs/DQM4HEP/build/lcio/src/LCIO-build/docbuild/html".
Call Stack (most recent call first):
  cmake_install.cmake:56 (INCLUDE)

make[3]: *** [install] Error 1
make[2]: *** [lcio/src/LCIO-stamp/LCIO-install] Error 2
make[1]: *** [CMakeFiles/LCIO.dir/all] Error 2
make: *** [all] Error 2

#############################################################################
ERRORS in the JSON related libraries (no doc or LCIO installation) 

bash-4.1$ cmake -DDQM4HEP_LCIO=OFF -DDQM4HEP_EXAMPLES=ON -DINSTALL_DOC=OFF -DDQM4HEP_VIZ=ON ..
-- DQM4HEP_VIZ: ON
-- DQM4HEP_LCIO: OFF
-- DQM4HEP_ELOG: OFF
-- DQM4HEP_EXAMPLES: ON
-- ILCSOFT not found
-- Could NOT find DIM_SHARED (missing:  DIM_SHARED_LIBRARY DIM_INCLUDE_DIR) 
-- Could NOT find DIM (missing:  DIM_LIBRARIES DIM_INCLUDE_DIR) 
-- Could NOT find DIMJC (missing:  DIMJC_LIBRARIES DIMJC_INCLUDE_DIRS) 
-- Check for DIMJC_INCLUDE_DIRS: DIMJC_INCLUDE_DIRS-NOTFOUND
-- Check for DIMJC_LIBRARIES: DIMJC_LIBRARY-NOTFOUND
-- 
-- -------------------------------------------------------------------------------
-- Change values with: cmake -D<Variable>=<Value>
-- CMAKE_INSTALL_PREFIX = /afs/desy.de/user/a/airqui/Programs/DQM4HEP
-- CMAKE_BUILD_TYPE = RelWithDebInfo
-- BUILD_TESTING = ON
-- INSTALL_DOC = OFF
-- CMAKE_MODULE_PATH =
--    /afs/desy.de/user/a/airqui/Programs/DQM4HEP/cmake;
-- -------------------------------------------------------------------------------
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /afs/desy.de/user/a/airqui/Programs/DQM4HEP/build

[ 50%] Performing build step for 'jsoncpp'
Scanning dependencies of target jsoncpp_lib
[ 11%] Building CXX object src/lib_json/CMakeFiles/jsoncpp_lib.dir/json_reader.cpp.o
[ 22%] Building CXX object src/lib_json/CMakeFiles/jsoncpp_lib.dir/json_value.cpp.o
[ 33%] Building CXX object src/lib_json/CMakeFiles/jsoncpp_lib.dir/json_writer.cpp.o
Linking CXX shared library libjsoncpp.so
[ 33%] Built target jsoncpp_lib
Scanning dependencies of target jsoncpp_lib_static
[ 44%] Building CXX object src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_reader.cpp.o
[ 55%] Building CXX object src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_value.cpp.o
[ 66%] Building CXX object src/lib_json/CMakeFiles/jsoncpp_lib_static.dir/json_writer.cpp.o
Linking CXX static library libjsoncpp.a
[ 66%] Built target jsoncpp_lib_static
Scanning dependencies of target jsontestrunner_exe
[ 77%] Building CXX object src/jsontestrunner/CMakeFiles/jsontestrunner_exe.dir/main.cpp.o
Linking CXX executable jsontestrunner_exe
[ 77%] Built target jsontestrunner_exe
Scanning dependencies of target jsoncpp_test
[ 88%] Building CXX object src/test_lib_json/CMakeFiles/jsoncpp_test.dir/jsontest.cpp.o
cc1plus: warnings being treated as errors
/afs/desy.de/user/a/airqui/Programs/DQM4HEP/jsoncpp/src/test_lib_json/jsontest.cpp: In member function ‘int JsonTest::Runner::runCommandLine(int, const char**) const’:
/afs/desy.de/user/a/airqui/Programs/DQM4HEP/jsoncpp/src/test_lib_json/jsontest.cpp:338: error: ‘testNameIndex’ may be used uninitialized in this function
make[5]: *** [src/test_lib_json/CMakeFiles/jsoncpp_test.dir/jsontest.cpp.o] Error 1
make[4]: *** [src/test_lib_json/CMakeFiles/jsoncpp_test.dir/all] Error 2
make[3]: *** [all] Error 2

**Comment by airqui** [comment]
I just tried after commit https://github.com/DQM4HEP/DQM4HEP/commit/3a588f58b9f42dfcc82b22769bd774432a2a3329

There is an error in the CMakeLists.txt, line 53, a missing ")"

SET( JsonCpp_additional_cmake_args "${JsonCpp_additional_cmake_args} -DJSONCPP_WITH_TESTS=OFF")

When I compile it, I still see errors:

###############################
If using -DINSTALL_DOC = ON

-- Installing: /space/airqui/Programs/DQM4HEP/doc/lcio/doxygen_api/html/classIOIMPL_1_1MCParticleIOImpl.png
-- Installing: /space/airqui/Programs/DQM4HEP/doc/lcio/lciorefman.ps
CMake Error at doc/cmake_install.cmake:44 (FILE):
  file INSTALL cannot find
  "/space/airqui/Programs/DQM4HEP/build/lcio/src/LCIO-build/docbuild/manual/manual_html".
Call Stack (most recent call first):
  cmake_install.cmake:56 (INCLUDE)


make[3]: *** [install] Error 1
make[2]: *** [lcio/src/LCIO-stamp/LCIO-install] Error 2
make[1]: *** [CMakeFiles/LCIO.dir/all] Error 2
make: *** [all] Error 2


###############################
If using -DINSTALL_DOC = OFF


[ 66%] Built target dimjc
Scanning dependencies of target dimjc_daemon
[100%] Building CXX object CMakeFiles/dimjc_daemon.dir/src/djc.cxx.o
Linking CXX executable bin/dimjc_daemon
/space/airqui/Programs/DQM4HEP/dim/linux/libdim.so: undefined reference to `sem_init'
/space/airqui/Programs/DQM4HEP/dim/linux/libdim.so: undefined reference to `sem_destroy'
/space/airqui/Programs/DQM4HEP/dim/linux/libdim.so: undefined reference to `pthread_create'
/space/airqui/Programs/DQM4HEP/dim/linux/libdim.so: undefined reference to `pthread_cancel'
/space/airqui/Programs/DQM4HEP/dim/linux/libdim.so: undefined reference to `sem_post'
/space/airqui/Programs/DQM4HEP/dim/linux/libdim.so: undefined reference to `sem_wait'
/space/airqui/Programs/DQM4HEP/dim/linux/libdim.so: undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[5]: *** [bin/dimjc_daemon] Error 1
make[4]: *** [CMakeFiles/dimjc_daemon.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [dimjc/src/dimjc-stamp/dimjc-build] Error 2
make[1]: *** [CMakeFiles/dimjc.dir/all] Error 2
make: *** [all] Error 2

**Comment by apingault** [comment]
Hi,

The first error while building the doc is really strange,
Cannot reproduce it for now ( Mac/Ubuntu15.10), will continue to investigate.

For dim this is probably a missing flag, try adding "-ltr" to LIBFLAGS in ${DIMDIR}/makefile_common

Cheers,
—
Antoine Pingault
PhD Student - Ghent University

On 11 Feb 2016, at 18:04, airqui <notifications@github.com<mailto:notifications@github.com>> wrote:


I just tried after commit 3a588f5<https://github.com/DQM4HEP/DQM4HEP/commit/3a588f58b9f42dfcc82b22769bd774432a2a3329>

There is an error in the CMakeLists.txt, line 53, a missing ")"

SET( JsonCpp_additional_cmake_args "${JsonCpp_additional_cmake_args} -DJSONCPP_WITH_TESTS=OFF")

When I compile it, I still see errors:

###############################
If using -DINSTALL_DOC = ON

-- Installing: /space/airqui/Programs/DQM4HEP/doc/lcio/doxygen_api/html/classIOIMPL_1_1MCParticleIOImpl.png
-- Installing: /space/airqui/Programs/DQM4HEP/doc/lcio/lciorefman.ps
CMake Error at doc/cmake_install.cmake:44 (FILE):
file INSTALL cannot find
"/space/airqui/Programs/DQM4HEP/build/lcio/src/LCIO-build/docbuild/manual/manual_html".
Call Stack (most recent call first):
cmake_install.cmake:56 (INCLUDE)

make[3]: *** [install] Error 1
make[2]: *** [lcio/src/LCIO-stamp/LCIO-install] Error 2
make[1]: *** [CMakeFiles/LCIO.dir/all] Error 2
make: *** [all] Error 2

###############################
If using -DINSTALL_DOC = OFF

[ 66%] Built target dimjc
Scanning dependencies of target dimjc_daemon
[100%] Building CXX object CMakeFiles/dimjc_daemon.dir/src/djc.cxx.o
Linking CXX executable bin/dimjc_daemon
/space/airqui/Programs/DQM4HEP/dim/linux/libdim.so: undefined reference to sem_init'
/space/airqui/Programs/DQM4HEP/dim/linux/libdim.so: undefined reference tosem_destroy'
/space/airqui/Programs/DQM4HEP/dim/linux/libdim.so: undefined reference to pthread_create'
/space/airqui/Programs/DQM4HEP/dim/linux/libdim.so: undefined reference topthread_cancel'
/space/airqui/Programs/DQM4HEP/dim/linux/libdim.so: undefined reference to sem_post'
/space/airqui/Programs/DQM4HEP/dim/linux/libdim.so: undefined reference tosem_wait'
/space/airqui/Programs/DQM4HEP/dim/linux/libdim.so: undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[5]: *** [bin/dimjc_daemon] Error 1
make[4]: *** [CMakeFiles/dimjc_daemon.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [dimjc/src/dimjc-stamp/dimjc-build] Error 2
make[1]: *** [CMakeFiles/dimjc.dir/all] Error 2
make: *** [all] Error 2

**Comment by airqui** [comment]
Hi Antoine,
Thanks for your answer. I just checked, being in the build directory, to add -ltr in the ../dim/makefile_common file 

"LIBFLAGS = -lpthread -ltr"

and type cmake again and make and I still receive the same error. 

Cheers,
Adrian

**Comment by rete** [comment]
Hi,

I fixed it by adding "-lpthread" flag in the **dimjc** top level CMakeLists.txt using : 
```cmake
ADD_DEFINITIONS(" -lpthread ")
```

Can you try to add it and give me your feedback ?

Cheers,

Rémi

**Comment by airqui** [comment]
Hi,
Still doesn't work... where exactly do you put this line? May you have done some extra changes since last commit?

Cheers,
Adrian

**Comment by apingault** [comment]
Restarting from scratch i now have the same problem with libdim on Ubuntu, not on mac. 
I’ll continue looking into that tomorrow.

**Comment by airqui** [comment]
good idea!

**Comment by apingault** [comment]
Hi,

Moving $(LIBFLAGS) to the end of the compiling command in makefile_dim  did the trick for the libdim problem. 
Found the info here : http://unix.stackexchange.com/questions/33396/gcc-cant-link-to-pthread

REPLACE:
makefile_dim:46:	$(CXX) $(LIBFLAGS) $(OBJS) $(UTILOBJS) $(UNIXOBJS) -o $(ODIR)/libdim.so
makefile_dim:49:	$(CXX) $(LIBFLAGS) $(OBJS) $(UTILOBJS) $(UNIXOBJS) $(JOBJS) -lgcc -o $(ODIR)/libjdim.so

By:
makefile_dim:46:	$(CXX) $(OBJS) $(UTILOBJS) $(UNIXOBJS) -o $(ODIR)/libdim.so  $(LIBFLAGS)
makefile_dim:49:	$(CXX) $(OBJS) $(UTILOBJS) $(UNIXOBJS) $(JOBJS) -lgcc -o $(ODIR)/libjdim.so  $(LIBFLAGS)

Can you confirm?

**Comment by airqui** [comment]
Hi, 
It works!
I tried the compilation with the default:

cmake ..

and also with 

cmake -DDQM4HEP_LCIO=ON -DDQM4HEP_EXAMPLES=ON ..

and worked completely ok. Still have the problem with the DOC, but I will try in other machine to see if the problem persists.

Thanks,
Adrian

**Comment by rete** [comment]
Hi,

many bugs were fixed during this review : 

* MySQL not found on some OS (lyoserv , SLC5), fixed by passing mysql location in -DMySQL_DIR=... via cmake cmd line
* dim shared library : missing pthread symbols leading to linking error in dimjc. Fixed by changing $(LIBFLAGS) as mentionned in the previous post.
* Missing install rule for dim package. Libs, includes and binaries were not installed at all. Install rule added
* jsoncpp tests and -Werror removed. Leaded to compilation error on uneeded stuff from jsoncpp
* bits/pthreadtypes.h does not exists on MACOSX. Fixed

For LCIO documentation generation, we found nothing on our side. Build procedure was tested on Debian 8, Ubuntu 15, MACOSX 10.11 and SLC5.

Regards, 

Rémi

**Comment by airqui** [comment]
Tested and working!
About the LCIO DOC, I have tried in Ubunt14 and Centos 7 and we still have an error:

CMake Error at doc/cmake_install.cmake:40 (FILE):
  file INSTALL cannot find
  "/home/calice/DQM4HEP/build/lcio/src/LCIO-build/docbuild/latex/lciorefman.ps".
Call Stack (most recent call first):
  cmake_install.cmake:56 (INCLUDE)


make[3]: *** [install] Error 1
make[2]: *** [lcio/src/LCIO-stamp/LCIO-install] Error 2
make[1]: *** [CMakeFiles/LCIO.dir/all] Error 2
make: *** [all] Error 2

But it works in SL6. 

I hope that this information would be useful for you. I can use the doxygen documentation already compiled in SL6 even if I run the code in other machine.

Cheers,
Adrian

**Comment by rete** [comment]
Hi,

it seems to be machine dependant. I'm maybe thinking about a missing software for doc install on your machine.
The file  "/home/calice/DQM4HEP/build/lcio/src/LCIO-build/docbuild/latex/lciorefman.ps" seems to be generated on-the-fly and doesn't seems to be present on your side.

Can you try with

```shell
make VERBOSE=1
```

and post the lcio stack here to see if some output can help.

Regards,

Rémi

**Comment by airqui** [comment]
Here they are the output and error files. The error is a bit different if you type make again., but seems to be related to the same thing that you pointed.

[stderr_2.txt](https://github.com/DQM4HEP/DQM4HEP/files/128081/stderr_2.txt)
[stderr_fromscratch.txt](https://github.com/DQM4HEP/DQM4HEP/files/128082/stderr_fromscratch.txt)
[stdout_2.txt](https://github.com/DQM4HEP/DQM4HEP/files/128084/stdout_2.txt)
[stdout_fromscratch.txt](https://github.com/DQM4HEP/DQM4HEP/files/128083/stdout_fromscratch.txt)

**Comment by rete** [comment]
Bug found ! 

In lcio/doc/CMakeLists.txt

we found that psnup (apt-get psutils) was not installed on one of our test machine (ubuntu 15.10). After installing psutils, the error vanishes.

Please can you check if psnup is installed on your side ?
Also, some other 'apt-get' packages for doc install maybe required and we will have to investigate this 'bug-report by bu-report'.

**Comment by airqui** [comment]
It was not installed in Centos7. After installing the psutils, the error vanished! :)

But, in the Ubuntu14, I do have the psutils installed since the begining...
psnup release 1 patchlevel 17

**Comment by rete** [comment]
Can you post the error you have ? An another package is maybe not installed.

**Comment by airqui** [comment]
[stderr_Ubuntu14.txt](https://github.com/DQM4HEP/DQM4HEP/files/128122/stderr_Ubuntu14.txt)
[stdout_Ubuntu14.txt](https://github.com/DQM4HEP/DQM4HEP/files/128121/stdout_Ubuntu14.txt)

**Comment by rete** [comment]
Bug found !

Again lcio/doc/CMakeLists.txt

lines 135 , 136 and 140. An error is raised while compiling the latex files. Fixed by adding ' | xargs' at each end of these lines, which gives us : 

```cmake
    ADD_CUSTOM_COMMAND(
        OUTPUT  "${DOC_BIN_DIR}/manual/manual.pdf"
        COMMAND "${LATEX_COMPILER}" -interaction=batchmode manual.tex | xargs
        COMMAND "${LATEX_COMPILER}" -interaction=batchmode manual.tex | xargs
        #COMMAND "${CMAKE_COMMAND}" -E echo "creating manual.ps"
        #COMMAND "${DVIPS_CONVERTER}" -q -o manual.ps manual.dvi
        COMMAND "${CMAKE_COMMAND}" -E echo "creating manual.pdf"
        COMMAND "${PDFLATEX_COMPILER}" -interaction=batchmode manual.tex  | xargs
        COMMAND "${CMAKE_COMMAND}" -E echo "creating manual_html"
        COMMAND "${LATEX2HTML_CONVERTER}" -mkdir -dir manual_html -verbosity 0 -info 0 -no_auto_link -split 0 -no_navigation manual.tex
        WORKING_DIRECTORY "${DOC_BIN_DIR}/manual"
        COMMENT "Building Documentation - Users Manual..."
        DEPENDS ${DOC_BIN_DIR}/manual
    )
```

instead of 

```cmake
    ADD_CUSTOM_COMMAND(
        OUTPUT  "${DOC_BIN_DIR}/manual/manual.pdf"
        COMMAND "${LATEX_COMPILER}" -interaction=batchmode manual.tex
        COMMAND "${LATEX_COMPILER}" -interaction=batchmode manual.tex
        #COMMAND "${CMAKE_COMMAND}" -E echo "creating manual.ps"
        #COMMAND "${DVIPS_CONVERTER}" -q -o manual.ps manual.dvi
        COMMAND "${CMAKE_COMMAND}" -E echo "creating manual.pdf"
        COMMAND "${PDFLATEX_COMPILER}" -interaction=batchmode manual.tex
        COMMAND "${CMAKE_COMMAND}" -E echo "creating manual_html"
        COMMAND "${LATEX2HTML_CONVERTER}" -mkdir -dir manual_html -verbosity 0 -info 0 -no_auto_link -split 0 -no_navigation manual.tex
        WORKING_DIRECTORY "${DOC_BIN_DIR}/manual"
        COMMENT "Building Documentation - Users Manual..."
        DEPENDS ${DOC_BIN_DIR}/manual
    )
```

Can you tell me if this is working.If yes, I will code a temporary patch in our software and send  abug report to LCIO developpers.

**Comment by airqui** [comment]
Solved!
:D

**Comment by rete** [comment]
Perfect ! :D 

The patch was push in commit 389836d6045933efb0ae884933f9f852c5dc2cb1.
Thanks for reporting these bugs.

We close the issue !

Regards,

Rémi & Antoine
