### ISSUE TITLE
Error When Compiling

### ISSUE THREAD

**Issue by tcoates3** [DQM4HEP/DQM4HEP#5]
When issuing the make command, I get a series of errors the cause the compilation to abort. My best guess is that it's something to do with directory structure not being interpreted correctly, which then causes the C++ compilation to fail, but I don't really understand make's error messages here. The command I'm using for the configuration is:

`cmake -DLOG4CXX_DIR=/home/t/tc/tc297/apps/log4cxx/0.10.0r1734552 -DBUILD_DQMVIZ=OFF -DBUILD_DQM4ILC=ON -DBUILD_EXAMPLES=ON -DDIM_GUI=ON ..`

It also fails in the same way if I add the `-C $ILCSOFT/ILCSoft.cmake` argument.  I've attached a copy of the error messages here: [MakeError.txt](https://github.com/DQM4HEP/DQM4HEP/files/173924/MakeError.txt)

**Comment by rete** [comment]
We recently changed the streaming interface to xdrstream. It seems that the change was not made on your side
Try to rebuild it from scratch.
Can you also post the full make output ( set doc to off to avoid too many messages ... ) ?

**Comment by tcoates3** [comment]
I re-cloned all the repos into a new folder then ran the installation again and got a different set of errors. I've attached the entire output [here](https://github.com/DQM4HEP/DQM4HEP/files/173979/MakeError2.txt) but the error message itself is:

`/lustre/scratch/epp/ilc/tc297/DQM2/DQM4HEP/DQMCore/source/src/DQMArchiver.cc: In member function ‘dqm4hep::StatusCode dqm4hep::DQMArchiver::open(const string&, const string&)’:
/lustre/scratch/epp/ilc/tc297/DQM2/DQM4HEP/DQMCore/source/src/DQMArchiver.cc:115:2: error: expected ‘;’ before ‘m_pArchiveFile’
  m_pArchiveFile = new TFile(m_fileName.c_str(), openingMode.c_str());
  ^
/lustre/scratch/epp/ilc/tc297/DQM2/DQM4HEP/DQMCore/source/src/DQMArchiver.cc:120:3: error: expected ‘;’ before ‘return’
   return STATUS_CODE_FAILURE;
   ^
/lustre/scratch/epp/ilc/tc297/DQM2/DQM4HEP/DQMCore/source/src/DQMArchiver.cc: In member function ‘dqm4hep::StatusCode dqm4hep::DQMArchiver::archive(dqm4hep::DQMModule*, bool)’:
/lustre/scratch/epp/ilc/tc297/DQM2/DQM4HEP/DQMCore/source/src/DQMArchiver.cc:158:2: error: expected ‘;’ before ‘m_pArchiveFile’
  m_pArchiveFile->cd();
  ^
make[5]: *** [source/CMakeFiles/DQMCore.dir/src/DQMArchiver.cc.o] Error 1
make[4]: *** [source/CMakeFiles/DQMCore.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [DQMCore/src/DQMCore-stamp/DQMCore-build] Error 2
make[1]: *** [CMakeFiles/DQMCore.dir/all] Error 2
make: *** [all] Error 2`

**Comment by rete** [comment]
I fixed the issues. 

DQMDbFileHandler and DQMMOnitorElementCollector were also affected.

It seems that depending on the LOG4CXX version you use, the ; character is needed or not after each LOG4CXX_* call. On my personnal laptop it was not. 
It seems that on your computer it is needed.

**Comment by tcoates3** [comment]
I've updated my repo of DQMCore and the error is still occurring for DQMArchiver. Do I need to make another clean install?

**Comment by rete** [comment]
Can you post the error message please ?

**Comment by tcoates3** [comment]
Here:

`[ 33%] Performing build step for 'DQMCore'
[  1%] Building CXX object source/CMakeFiles/DQMCore.dir/src/DQMArchiver.cc.o
/lustre/scratch/epp/ilc/tc297/DQM2/DQM4HEP/DQMCore/source/src/DQMArchiver.cc: In member function ‘dqm4hep::StatusCode dqm4hep::DQMArchiver::open(const string&, const string&)’:
/lustre/scratch/epp/ilc/tc297/DQM2/DQM4HEP/DQMCore/source/src/DQMArchiver.cc:115:2: error: expected ‘;’ before ‘m_pArchiveFile’
  m_pArchiveFile = new TFile(m_fileName.c_str(), openingMode.c_str());
  ^
/lustre/scratch/epp/ilc/tc297/DQM2/DQM4HEP/DQMCore/source/src/DQMArchiver.cc:120:3: error: expected ‘;’ before ‘return’
   return STATUS_CODE_FAILURE;
   ^
/lustre/scratch/epp/ilc/tc297/DQM2/DQM4HEP/DQMCore/source/src/DQMArchiver.cc: In member function ‘dqm4hep::StatusCode dqm4hep::DQMArchiver::archive(dqm4hep::DQMModule*, bool)’:
/lustre/scratch/epp/ilc/tc297/DQM2/DQM4HEP/DQMCore/source/src/DQMArchiver.cc:158:2: error: expected ‘;’ before ‘m_pArchiveFile’
  m_pArchiveFile->cd();
  ^
make[5]: *** [source/CMakeFiles/DQMCore.dir/src/DQMArchiver.cc.o] Error 1
make[4]: *** [source/CMakeFiles/DQMCore.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [DQMCore/src/DQMCore-stamp/DQMCore-build] Error 2
make[1]: *** [CMakeFiles/DQMCore.dir/all] Error 2
make: *** [all] Error 2`

**Comment by rete** [comment]
Try to enter the DQMCore directory in DQM4HEP/DQMCore and type

```bash
git pull
```

to see if there are some changes operating.

**Comment by tcoates3** [comment]
That's fixed the issue with DQMArchiver but now it fails to compile DQMMonitorElementCollector with similar semicolon errors:

`[ 27%] Building CXX object source/CMakeFiles/DQMCore.dir/src/DQMMonitorElementCollector.cc.o
/lustre/scratch/epp/ilc/tc297/DQM2/DQM4HEP/DQMCore/source/src/DQMMonitorElementCollector.cc: In member function ‘virtual void dqm4hep::DQMMonitorElementNameListRpc::rpcHandler()’:
/lustre/scratch/epp/ilc/tc297/DQM2/DQM4HEP/DQMCore/source/src/DQMMonitorElementCollector.cc:1355:3: error: expected ‘;’ before ‘setData’
   setData((void*) m_pCollector->m_pOutBuffer->getBuffer(), m_pCollector->m_pOutBuffer->getPosition());
   ^
make[5]: *** [source/CMakeFiles/DQMCore.dir/src/DQMMonitorElementCollector.cc.o] Error 1
make[4]: *** [source/CMakeFiles/DQMCore.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [DQMCore/src/DQMCore-stamp/DQMCore-build] Error 2
make[1]: *** [CMakeFiles/DQMCore.dir/all] Error 2
make: *** [all] Error 2`

**Comment by rete** [comment]
Fixed.
Try again

**Comment by tcoates3** [comment]
Okay, that's fixed it. Thanks very much!
